# -*- coding: utf-8 -*-
"""DNA_SEQUENCE_ANALYSER_ADWEETA26MIB10087.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qK4LzIUpm29-Lt1rR5mnacCdD-PQVFM1
"""

def analyze_sequence(sequence):

    length = len(sequence)

    a_count = sequence.count("A")
    t_count = sequence.count("T")
    g_count = sequence.count("G")
    c_count = sequence.count("C")

    a_percentage = (a_count / length) * 100
    t_percentage = (t_count / length) * 100
    g_percentage = (g_count / length) * 100
    c_percentage = (c_count / length) * 100

    gc_content = ((g_count + c_count) / length) * 100
    at_content = ((a_count + t_count) / length) * 100

    print("Length:", length)

    print("A:", a_count)
    print("T:", t_count)
    print("G:", g_count)
    print("C:", c_count)

    print("A percentage:", round(a_percentage, 2), "%")
    print("T percentage:", round(t_percentage, 2), "%")
    print("G percentage:", round(g_percentage, 2), "%")
    print("C percentage:", round(c_percentage, 2), "%")

    print("GC Content:", round(gc_content, 2), "%")
    print("AT Content:", round(at_content, 2), "%")

print("====================================")
print("       DNA sequence anlyser         ")
print("====================================")


strand1 = input("Enter first DNA strand: ").upper()

print("\n===== STRAND 1 ANALYSIS =====")
analyze_sequence(strand1)

strand2 = input("\nEnter second DNA strand: ").upper()

print("\n===== STRAND 2 ANALYSIS =====")
analyze_sequence(strand2)

complement = ""

for base in strand1:
    if base == "A":
        complement += "T"
    elif base == "T":
        complement += "A"
    elif base == "G":
        complement += "C"
    elif base == "C":
        complement += "G"

print("\n===== COMPARISON =====")

print("Strand 1:", strand1)
print("Strand 2:", strand2)
print("Complement of Strand 1:", complement)

if complement == strand2:
    print("Result: The two strands are complementary!")
else:
    print("Result: The two strands are NOT complementary.")